version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      include: "scope"
      prefix: "ci"
  - package-ecosystem: "npm"
    groups:
      "npm":
        patterns:
          - "markdownlint-cli2"
          - "cspell"
          - "@cspell/dict-uk-ua"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      include: "scope"
      prefix: "chore"