version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      include: "scope"
      prefix: "ci(deps):"
  - package-ecosystem: "npm"
    groups:
      "npm":
        patterns:
          - "markdownlint-cli2"
          - "cspell"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      include: "scope"
      prefix: "chore(deps):"